### PR TITLE
Skeleton version of this library (CU-baqucz)

### PR DESCRIPTION
**Pull request by trisapeace**
The package skeleton for this library:
* CHANGELOG.md
* README.md
* .gitignore
* A test that always passes
* Linting
* Travis which runs the linting and the tests
* Tagged with `v0.1.0`

The dummy implementation is a class with a single function that prints "BraveAlertLib here" to the console. We can see that this can be included using the `v0.1.0` tag and called in both these PRs:
* [BraveButtons/chatbot](https://github.com/bravetechnologycoop/BraveButtons/pull/46), and
* [ODetect-Backend-Local](https://github.com/bravetechnologycoop/ODetect-Backend-Local/pull/47)

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-baqucz Install skeleton version of brave-alert-lib in Chatbot and ODetect](https://app.clickup.com/t/baqucz)

**Comment by sampathsatti** [comment]
Looks good to me! 

The only other thing that I think might be useful to call out at this stage (perhaps add to local dev setup instructions in readme) itself is how the brave-alert-lib will be imported into the Button/ODetect apps?

**Review by sampathsatti — APPROVED** [review]

**Comment by trisapeace** [comment]
I think that's a good idea, @sampathsatti . I'll add that to the README.

**Comment by schwarrrtz** [comment]
looks like i can't review now that this has been merged - but LGTM!

**Pull request merged**
